planner_logic_plugin_name: "moveit_hybrid_planning/ReplanInvalidatedTrajectory"
local_planning_action_name: "local_planning_action"
global_planning_action_name: "global_planning_action"
hybrid_planning_action_name: "hybrid_planning_action"
