depth_camera_bridge:
  ros__parameters:
    topic_name: "/depth_camera/points"
    ros_type_name: "sensor_msgs/msg/PointCloud2"
    gz_type_name: "gz.msgs.PointCloudPacked"
    direction: BIDIRECTIONAL