move_group:
  ros__parameters:
    
    # Planning parameters
    plan_execution:
      max_replan_attempts: 10
      record_trajectory_state_frequency: 0.0
    
    # Planning pipeline configuration
    planning_pipelines:
      ompl:
        planning_plugin: ompl_interface/OMPLPlanner
        request_adapters: >
          default_planner_request_adapters/AddTimeParameterization
          default_planner_request_adapters/FixWorkspaceBounds
          default_planner_request_adapters/FixStartStateBounds
          default_planner_request_adapters/FixStartStateCollision
          default_planner_request_adapters/FixStartStatePathConstraints
        start_state_max_bounds_error: 0.1
      
        
    
    # Planning scene monitor configuration
    planning_scene_monitor:
      publish_planning_scene: true
      publish_geometry_updates: true
      publish_state_updates: true
      publish_transforms_updates: true
      robot_description: robot_description

    octomap_frame: map  # должен совпадать с frame_id приходящей OctoMap
    octomap_resolution: 0.10

    sensors:
      - sensor_plugin: occupancy_map_monitor/OctomapUpdater
        octomap_topic: /octomap/example
        max_update_rate: 1.0

planner_configs:
  RRTstar:
    type: geometric::RRTstar
    range: 1.0
  PRMstar:
    type: geometric::PRMstar

group_configs:
  drone_group:
    default_planner_config: RRTstar
    # важно: НЕ принуждаем joint-space; для floating будет PoseModelStateSpace (SE3)
    enforce_joint_model_state_space: false
    # Рабочая область (метры)
    minx: -20.0; maxx: 20.0
    miny: -20.0; maxy: 20.0
    minz:  0.5;  maxz: 10.0
