moveit_simple_controller_manager:
  ros__parameters:
    controller_names:
      - drone_controller

    drone_controller:
      type: FollowJointTrajectory
      joints:
        - virtual_joint
      action_ns: follow_joint_trajectory
      default: true
