ompl:
  ros__parameters:
    planner_configs:
      RRTstar:
        type: geometric::RRTstar
        range: 0.0
      RRTConnect:
        type: geometric::RRTConnect
        range: 0.0
      PRMstar:
        type: geometric::PRMstar
        range: 0.0

    planning_time: 5.0
    max_velocity_scaling_factor: 1.0
    max_acceleration_scaling_factor: 1.0
    # <- можно добавить и другие опции, которые были в вашем старом YAML
